linters:
  enable:
    - gofmt
    - goimports
    - govet
    - stylecheck
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - revive

linters-settings:
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: var-naming
        disabled: false

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
  go: "1.22"
  memory:
    max-per-linter: 100MB
    max-total: 500MB

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck